version: '3'
services:
  app:
    stdin_open: true
    tty: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      # Mounts the app code (".") into the container's "/app" folder:
      - .:/app:delegated

      # Mounts a persistable volume in the installed gems folder, so we can add
      # gems to the app without having to build the development image again:
      - app-gems:/usr/local/bundle
      # Mounts a clean tmp folder everytime
      - /app/tmp
      - /tmp
    depends_on:
      - redis

    ports:
      - "3000:3000"
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

  redis:
    image: redis
    ports:
      - "6379:6379"

  sidekiq:
    build: .
    command: bundle exec sidekiq -q default
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

volumes:
  app-gems:
    driver: local
